<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>HRS.Shared.Core</PackageId>
        <Authors>Feri Setiawan</Authors>
        <Company>HRS</Company>
        <Description>Shared DTOs, Enums, and Interfaces for HRS microservices</Description>
        <PackageOutputPath>./nupkg</PackageOutputPath>
    </PropertyGroup>

</Project>
